### ISSUE TITLE
Example Notebook Error 

### ISSUE THREAD

**Issue by bartlettnbb2** [Rkoost/PyQCAMS#1]
Hello,

I am a researcher at the University of Illinois at Urbana-Champaign and I want to use/ develop on your code. The notebook errors upon initial use. See output below:

KeyError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 calc = pymar.start('inputs.json')

File ~/anaconda3/lib/python3.10/site-packages/pyqcams/pymar.py:775, in start(input_file)
    773 with open(f'{input_file}') as f:
    774     data = json.load(f)
--> 775 potential_AB = data['potential_AB'] # which potential
    776 potential_BC = data['potential_BC']
    777 potential_CA = data['potential_CA']

KeyError: 'potential_AB'

I will be working on this with my colleague as well who recently pulled the code as well. Looking forward to working with you.

-Nathan Bartlett

**Comment by Rkoost** [comment]
Hello Nathan,

Thank you for joining, I am looking forward to working with you as well!
I've changed the input file system, where `inputs.json` only contains calculation parameters. The potentials are now added via the `input_v.py` file. `pymar.start()` now takes the directory containing these two files. I've updated the repository, so reinstalling the program should work now.

**Comment by bartlettnbb2** [comment]
Ok this works, thank you!
